// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "apiKey": string;
      "defaultProject": string;
      "heartbeatInterval": number;
      "includeTitle": boolean;
      "showToolbarIcon": boolean;
      "apiBaseUrl": string;
    };
  }
}
